project:
  type: website
  output-dir: docs

website:
  title: "PM566-Final-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Dataset.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


